version: '3'

includes:
  docs:
    taskfile: ./docs/Taskfile.yml
    dir: ./docs

tasks:
  install:
    desc: "Install pocketchemist-nmr"
    cmds:
      - pip install .

  develop:
    desc: "Install pocketchemist-nmr in (editable) developer mode"
    cmds:
      - pip install --editable .'[tests,docs]'

  updload:
    desc: "Upload package to pypi"
    cmds:
      - python3 -m build --sdist --wheel
      - twine check dist/*
      - twine upload dist/*

  build:
    desc: Build datasets needed for tests
    cmds:
      - task -d data/bruker/CD20170124_av500hd_100_ubq_oneone1d/ build
      - task -d data/bruker/CD20170124_av500hd_101_ubq_hsqcsi2d/ build
      - task -d data/bruker/CD20170124_av500hd_103_ubq_hnco3d/ build

  clean:
    desc: Clean (remove) test datasets
    cmds:
      - find data/bruker -name "*.fid" -delete
      - find data/bruker -name "*.ft" -delete
      - find data/bruker -name "*.ft1" -delete
      - find data/bruker -name "*.ft2" -delete
      - find data/bruker -name "*.ft3" -delete
      - find data/bruker -name "*.hdr" -delete

  test:
    desc: Run pytests
    deps: [build]
    cmds:
      - pytest

