version: '3'

tasks:
  build:
    desc: Build datasets needed for tests
    cmds:
      - task -d data/bruker/CD20170124_av500hd_100_ubq_oneone1d/ build
      - task -d data/bruker/CD20170124_av500hd_101_ubq_hsqcsi2d/ build

  test:
    desc: Run pytests
    deps: [build]
    cmds:
      - pytest
